linters:
  enable:
  # golangci-lint defaults 
  # ref: https://golangci-lint.run/usage/linters/#enabled-by-default
  - errcheck
  - govet
  - ineffassign
  - unused
  # additional
  - misspell
  - gofmt
  fast: true
  disable:
  - gosimple
  - staticcheck
run:
  timeout: 5m