// Copyright 2024 OpenPubkey
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

package mocks

import (
	"context"
	"crypto/rand"
	"crypto/rsa"
	"encoding/json"
	"fmt"
	"time"

	"github.com/lestrrat-go/jwx/v2/jwa"
	"github.com/lestrrat-go/jwx/v2/jws"
	"github.com/openpubkey/openpubkey/pktoken"
	"github.com/openpubkey/openpubkey/pktoken/clientinstance"
	"github.com/openpubkey/openpubkey/providers"
	"github.com/openpubkey/openpubkey/providers/discover"
	"github.com/openpubkey/openpubkey/verifier"
	"github.com/stretchr/testify/mock"
)

// OpenIdProvider is an autogenerated mock type for the OpenIdProvider type
type OpenIdProvider struct {
	mock.Mock
	issuer          string
	PublicKeyFinder discover.PublicKeyFinder
	verifier        verifier.ProviderVerifier
}

func (_m *OpenIdProvider) PublicKeyByKeyId(ctx context.Context, keyID string) (*discover.PublicKeyRecord, error) {
	return _m.PublicKeyFinder.ByKeyID(ctx, _m.issuer, keyID)
}

func (_m *OpenIdProvider) PublicKeyByJTK(ctx context.Context, jtk string) (*discover.PublicKeyRecord, error) {
	return _m.PublicKeyFinder.ByJTK(ctx, _m.issuer, jtk)
}

func (_m *OpenIdProvider) PublicKeyByToken(ctx context.Context, token []byte) (*discover.PublicKeyRecord, error) {
	return _m.PublicKeyFinder.ByToken(ctx, _m.issuer, token)
}

// RequestTokens provides a mock function with given fields: ctx, cicHash
func (_m *OpenIdProvider) RequestTokens(ctx context.Context, cic *clientinstance.Claims) ([]byte, error) {
	// Define our commitment as the hash of the client instance claims
	cicHashBytes, err := cic.Hash()
	if err != nil {
		return nil, fmt.Errorf("error calculating client instance claim commitment: %w", err)
	}
	cicHash := string(cicHashBytes)

	ret := _m.Called(ctx, cicHash)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, cicHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, cicHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cicHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *OpenIdProvider) Issuer() string {
	return _m.issuer
}

func (_m *OpenIdProvider) VerifyProvider(ctx context.Context, pkt *pktoken.PKToken) error {
	return _m.verifier.VerifyProvider(ctx, pkt)
}

// NewOpenIdProvider creates a new instance of OpenIdProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOpenIdProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *OpenIdProvider {
	mock := &OpenIdProvider{}
	mock.Mock.Test(t)

	return mock
}

type MockProviderOpts struct {
	GQSign       bool
	GQCommitment bool
	GQOnly       bool
}
type Opts func(a *MockProviderOpts)

// Example use:
//
//	UseGQSign(true)
func UseGQSign(gqSign bool) Opts {
	return func(m *MockProviderOpts) {
		m.GQSign = gqSign
	}
}

// UseGQCommitment specifies whether the commitment binding should be a GQ
// binding or a claim based binding.
// Example use:
//
//	UseGQCommitment(true)
func UseGQCommitment(gqCommitment bool) Opts {
	return func(m *MockProviderOpts) {
		m.GQCommitment = gqCommitment
	}
}

// Example use:
//
//	UseGQOnly(true)
func UseGQOnly(gqOnly bool) Opts {
	return func(m *MockProviderOpts) {
		m.GQOnly = gqOnly
	}
}

// This function creates a new, correctly functioning Provider that can be used for test purposes, for finer grain control
// or error testing, please use the function above.
//
// extraClaims: Allows for optional id token payload values to be supplied, these values will overwrite existing ones of the same name.
func NewMockOpenIdProvider(
	t interface {
		mock.TestingT
		Cleanup(func())
	},
	extraClaims map[string]any,
	opts ...Opts,
) (*OpenIdProvider, error) {
	providerOpts := &MockProviderOpts{
		GQSign:       false,
		GQCommitment: false,
		GQOnly:       false,
	}
	for _, applyOpt := range opts {
		applyOpt(providerOpts)
	}

	alg := jwa.RS256
	signingKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return nil, err
	}

	oidpServer, err := NewOIDPServer(signingKey, alg)
	if err != nil {
		return nil, err
	}
	if err := oidpServer.Serve(); err != nil {
		return nil, err
	}
	t.Cleanup(func() { oidpServer.Shutdown() })

	// Use our OIDP server uri as the mock issuer
	issuer := oidpServer.URI()
	jwksFunc, err := discover.MockGetJwksByIssuerOneKey(signingKey.Public(), oidpServer.KID(), string(alg))
	if err != nil {
		return nil, err
	}

	provider := NewOpenIdProvider(t)
	provider.PublicKeyFinder.JwksFunc = jwksFunc
	provider.issuer = issuer

	commitmentClaim := "nonce"
	if providerOpts.GQCommitment {
		commitmentClaim = ""
	}

	provider.verifier = providers.NewProviderVerifier(
		issuer, commitmentClaim,
		providers.ProviderVerifierOpts{
			GQCommitment: providerOpts.GQCommitment,
			GQOnly:       providerOpts.GQOnly,
			// TODO: The default should be false
			// Tracking this issue in https://github.com/openpubkey/openpubkey/issues/147
			SkipClientIDCheck: true},
	)

	provider.On("RequestTokens", mock.Anything, mock.Anything).Return(func(ctx context.Context, cicHash string) ([]byte, error) {
		headers := jws.NewHeaders()
		headers.Set(jws.AlgorithmKey, alg)
		headers.Set(jws.KeyIDKey, oidpServer.KID())
		headers.Set(jws.TypeKey, "JWT")

		// Default, minimum viable claims for functional id token payload
		payload := map[string]any{
			"sub": "me",
			"aud": "also me",
			"iss": issuer,
			"iat": time.Now().Unix(),
		}

		// Don't set a claim commitment if we are using a GQ commitment
		if !providerOpts.GQCommitment {
			// TODO: Handle the case where we are using a different claim, e.g. aud
			// Tracking this issue in https://github.com/openpubkey/openpubkey/issues/146
			payload["nonce"] = cicHash
		}
		// Add/replace values in payload map with those provided
		for k, v := range extraClaims {
			payload[k] = v
		}

		payloadBytes, err := json.Marshal(payload)
		if err != nil {
			return nil, err
		}

		token, err := jws.Sign(
			payloadBytes,
			jws.WithKey(
				alg,
				signingKey,
				jws.WithProtectedHeaders(headers),
			),
		)

		if providerOpts.GQCommitment && !providerOpts.GQSign {
			// Catch misconfigurations
			return nil, fmt.Errorf("if GQCommitment is true then GQSign must also be true")
		}
		if providerOpts.GQSign {
			if providerOpts.GQCommitment {
				return providers.CreateGQBoundToken(ctx, token, provider, cicHash)
			} else {
				return providers.CreateGQToken(ctx, token, provider)
			}
		}

		return token, err
	})

	return provider, nil
}
